# Generated by Django 4.2.15 on 2024-08-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='availibility',
            new_name='availability',
        ),
    ]
