# Generated by Django 4.2.15 on 2024-09-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_remove_cart_color_remove_cart_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='itemsid',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
