# Generated by Django 4.2.15 on 2024-09-25 18:21

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_order_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
